---
-
  hosts: zookeeper
  name: "test ansible"
  strategy: free
  tasks:
      -
        name: Run some command
        command: /bin/whoami
        ignore_errors: true
        register: command_output1
        become: yes
      -
        debug:
          var: command_output1
        name: Command 1 output

